/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          50: '#f0f9ff',
          100: '#e0f2fe',
          500: '#0ea5e9',
          600: '#0284c7',
          700: '#0369a1',
          900: '#0c4a6e',
          DEFAULT: "#0037b0"
        },
        sidebar: '#111827',
        "tertiary-fixed-dim": "#bec6e0",
        "on-error-container": "#93000a",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        "tertiary-fixed": "#dae2fd",
        "tertiary": "#3d445a",
        "on-tertiary-container": "#cdd5ef",
        "on-secondary-fixed": "#0b1c30",
        "on-primary-fixed-variant": "#0039b5",
        "on-secondary-container": "#54647a",
        "on-primary": "#ffffff",
        "error": "#ba1a1a",
        "primary-fixed": "#dce1ff",
        "surface-tint": "#2151da",
        "on-secondary-fixed-variant": "#38485d",
        "on-tertiary-fixed": "#131b2e",
        "surface": "#f7f9fb",
        "on-tertiary": "#ffffff",
        "on-surface-variant": "#434655",
        "tertiary-container": "#545c72",
        "primary-container": "#1d4ed8",
        "on-tertiary-fixed-variant": "#3f465c",
        "inverse-surface": "#2d3133",
        "surface-variant": "#e0e3e5",
        "on-error": "#ffffff",
        "surface-container": "#eceef0",
        "on-primary-fixed": "#001551",
        "surface-container-low": "#f2f4f6",
        "outline-variant": "#c4c5d7",
        "on-surface": "#191c1e",
        "surface-container-highest": "#e0e3e5",
        "inverse-on-surface": "#eff1f3",
        "surface-dim": "#d8dadc",
        "on-secondary": "#ffffff",
        "secondary-fixed-dim": "#b7c8e1",
        "background": "#f7f9fb",
        "primary-fixed-dim": "#b7c4ff",
        "secondary-container": "#d0e1fb",
        "inverse-primary": "#b7c4ff",
        "secondary-fixed": "#d3e4fe",
        "on-primary-container": "#cad3ff",
        "secondary": "#505f76",
        "outline": "#747686",
        "surface-bright": "#f7f9fb",
        "on-background": "#191c1e",
        "surface-container-high": "#e6e8ea"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "unit": "4px",
        "gutter": "16px",
        "density-low": "24px",
        "container-margin": "24px",
        "density-medium": "16px",
        "density-high": "8px"
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        "h2": ["Inter", "sans-serif"],
        "data-mono": ["JetBrains Mono", "monospace"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "h3": ["Inter", "sans-serif"],
        "h1": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"]
      },
      fontSize: {
        "h2": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "data-mono": ["13px", { "lineHeight": "16px", "fontWeight": "500" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "body-sm": ["12px", { "lineHeight": "18px", "fontWeight": "400" }],
        "h3": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "h1": ["30px", { "lineHeight": "38px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "label-caps": ["11px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "700" }]
      }
    },
  },
  plugins: [],
}
