services:
  postgres:
    image: postgres:16
    container_name: nexora-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: prince
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: business_operations

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: nexora-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  postgres_data: