services:
  postgres:
    image: postgres:16
    container_name: nexora-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: prince
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: business_operations

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: